services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "test1"

  rcmenu:
    build: .
    command: npm start
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "mysql://root:test1@db:3306/RCMenu"
    depends_on:
      - db