services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./../db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: uimenu
      MYSQL_ROOT_PASSWORD: "test1"

  uimenu:
    build: .
    command: npm start
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "mysql://root:test1@db:3306/uimenu"
      EMAIL_HOST: "live.smtp.mailtrap.io"
      EMAIL_PORT: 587
      EMAIL_USER: "api"
      EMAIL_PASS: "31d44f1c8ebb485ce777dac37de159cb"
    depends_on:
      - db