services:
  uimenu:
    image: "sgad/uimenu:v1.0.3"
    command: npm start
    ports:
      - 80:3000
    environment:
      DATABASE_URL: ""
      EMAIL_HOST: "live.smtp.mailtrap.io"
      EMAIL_PORT: 587
      EMAIL_USER: "api"
      EMAIL_PASS: "31d44f1c8ebb485ce777dac37de159cb"
    restart: unless-stopped